name: Build

on:
    push:
      tags:
        - 'v*'

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
              os: [macos-latest, ubuntu-latest]
              arch: [x86_64, arm64]
              python-version: [3.10, 3.11]
        
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-python@v4
            with:
                python-version: ${{ matrix.python-version }}
                architecture: ${{ matrix.arch }}
          - name: Step C++
            uses: aminya/setup-cpp@v1
            with:
                compiler: g++-11
          - name: Install dependencies
            run: pip install -r requirements.txt
          - name: Build wheel
            run: python setup.py bdist_wheel
          - name: Upload artifact
            uses: actions/upload-artifact@v3
            with:
                name: nes-py-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.python-version }}
                path: dist/*.whl